//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurveySysDAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        public Cliente()
        {
            this.RespostaSet = new HashSet<Resposta>();
        }
    
        public int id { get; set; }
        public int tipousuario_id { get; set; }
        public string nome { get; set; }
        public string telefone { get; set; }
        public string email { get; set; }
        public string usuario { get; set; }
        public string senha { get; set; }
    
        public virtual TipoUsuario TipoUsuarioSet { get; set; }
        public virtual ICollection<Resposta> RespostaSet { get; set; }
    }
}
