//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurveySysDAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pergunta
    {
        public Pergunta()
        {
            this.AlternativaSet = new HashSet<Alternativa>();
            this.QuestionarioSet = new HashSet<Questionario>();
        }
    
        public int id { get; set; }
        public int tipopergunta_id { get; set; }
        public string enunciado { get; set; }
    
        public virtual ICollection<Alternativa> AlternativaSet { get; set; }
        public virtual TipoPergunta TipoPerguntaSet { get; set; }
        public virtual ICollection<Questionario> QuestionarioSet { get; set; }
    }
}
