//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurveySysDAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resposta
    {
        public int id { get; set; }
        public int cliente_id { get; set; }
        public int alternativa_id { get; set; }
    
        public virtual Alternativa AlternativaSet { get; set; }
        public virtual Cliente ClienteSet { get; set; }
    }
}
